[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.4.0", "hatch-nodejs-version", "jupyterlab>=4.0.0"]

[project]
name = "jupyter-webrtc-provider-monorepo"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
  # jupyter-server extensions
  "jupyter-server-signaling @ {root:uri}/projects/jupyter-server-signaling",
  # jupyterlab/notebook frontend extensions
  "jupyter-webrtc-provider @ {root:uri}/projects/jupyter-webrtc-provider",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "click",
    "pre-commit",
    "jupyter_releaser",
    "tomlkit"
]

[tool.hatch.version]
source = "nodejs"

[tool.hatch.build]
packages = [
  "projects/jupyter-server-signaling",
  "projects/jupyter-webrtc-provider",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.jupyter-releaser]
skip = ["check-links", "check-python"]

[tool.jupyter-releaser.options]
# `--skip-if-dirty` is a workaround for https://github.com/jupyter-server/jupyter_releaser/issues/567
version-cmd = "cd ../.. && python scripts/bump_version.py --force --skip-if-dirty"
python_packages = [
    "projects/jupyter-server-signaling:jupyter-server-signaling",
    "projects/jupyter-webrtc-provider:jupyter-webrtc-provider",
]

[tool.jupyter-releaser.hooks]
before-build-npm = [
    "YARN_ENABLE_IMMUTABLE_INSTALLS=0 jlpm build:prod"
]
before-build-python = [
    "jlpm clean:all",
    # Build the assets
    "jlpm build:prod",
    # Clean the build artifacts to not include them in sdist
    "jlpm clean:lib"
]
before-bump-version = [
    "python -m pip install -U jupyterlab tomlkit",
    "jlpm"
]
