[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.4.0"]

[project]
name = "jupyter-server-signaling"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
classifiers = [
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Framework :: Jupyter"
]
authors = [
    { name = "David Brochart", email = "david.brochart@gmail.com" },
]
dependencies = [
  "jupyter_server >=2.15.0,<3.0.0",
  "jupyter-docprovider >=2.4.0,<3.0.0",
  "jupyter-collaboration-ui >=2.4.0,<3.0.0",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/davidbrochart/jupyter-webrtc-provider"

[tool.hatch.version]
path = "jupyter_server_signaling/_version.py"

[tool.hatch.build.targets.sdist]
exclude = ["/.github", "/binder", "node_modules"]

[tool.hatch.build.targets.wheel.shared-data]
"jupyter-config/jupyter_server_signaling.json" = "etc/jupyter/jupyter_server_config.d/jupyter_server_signaling.json"

[tool.check-wheel-contents]
ignore = ["W002"]
